name: 'send message'
description: 'message to im when build is finished for example'
inputs:
  message:
    description: Custom message for send
    required: true
runs:
  using: composite
  steps:
    - name: 'Let the world know!'
      shell: bash
      run: |
        echo "### Building build ${{ inputs.message }}" >> $GITHUB_STEP_SUMMARY

