name: 'build prod-ready app'
description: 'this is a description'

inputs:
  build-number:
    description: Build Number
    required: true

runs:
  using: composite
  steps:
    - name: build
      shell: bash
      env:
        BUILD_NUMBER: ${{ inputs.build-number }}
      run: dotnet build --configuration Release DevschoolCiTest.sln