name: build and deploy live translation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo stuff'
        run: echo 'build'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.100
      - name: Build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{ github.run_number }}
      - name: Publish
        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend src/devschool-ci-test.csproj
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: selfdeceited
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./artifacts/backend/Dockerfile
          github-token: ${{ secrets.GHCR_PUBLISH_TOKEN }}
          push: true
          context: .
          tags: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}-live
          build-args: |
            "GH_BUILD_NUMBER=${{ github.run_number }}"
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: human-atalanta
          service-name: devschool-ci-test
          service-instance-type: free
          docker: ghcr.io/selfdeceited/devschool-ci-test:${{ inputs.image_number }}-live
          docker-private-registry-secret: ghrc_cred
