name: Build and test
on:
  push:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
      - name: build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{github.run_number}}
      - name: test
        id: check-step-id
        run: dotnet test DevSchool.Ci.sln
  notification:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Set status if check success
        if: ${{ steps.check-step-id.outcome == 'success' }}
        run: echo "CHECK_RESULT_MESSAGE=✅App was build and test success with number build is ${{ github.run_number }}" >> $GITHUB_ENV
      - name: Set status icon if check failed
        if: ${{ steps.check-step-id.outcome == 'failure' || steps.check-step-id.outcome == 'cancelled' }}
        run: echo "CHECK_RESULT_MESSAGE=❌App build and test failed with number build is ${{ github.run_number }}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4
      - name: send message
        uses: ./.github/actions/loop-send-message
        with:
          message: ${{ env.CHECK_RESULT_MESSAGE }}
          url: ${{ secrets.LOOP_URL }}
