name: 'Build and deploy app :)'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
      - name: build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{github.run_number}}
      - name: publish artifacts
        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend devschool-ci-test.csproj
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: selfdeceited
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./artifacts/backend/Dockerfile
          github-token: ${{ secrets.GHCR_PUBLISH_TOKEN }}
          push: true
          context: .
          tags: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: human-atalanta
          service-name: devschool-ci-test
          service-instance-type: free
          docker: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}
          docker-private-registry-secret: ghrc_cred