name: 'Build and deploy app :)'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
      - name: build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{github.run_number}}
      - name: publish artifacts
        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend devschool-ci-test.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - run: echo 'deployy!'
