name: build and deploy live translation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo stuff'
        run: echo 'build'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.100
      - name: Build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{ github.run_number }}
        

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy'
