name: 'Build and deploy app :)'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - run: echo 'deployy!'
