name: Build and test
on:
  push:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'
      - name: build
        uses: ./.github/actions/build-app
        with:
          build-number: ${{github.run_number}}
      - name: tests
        run: dotnet test DevSchool.Ci.sln
  #      - name: publish artifacts
  #        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend src/devschool-ci-test.csproj
  #      - name: Login to GitHub container registry
  #        uses: docker/login-action@v3
  #        with:
  #          registry: ghcr.io
  #          username: selfdeceited
  #          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
  #      - name: Build and push image
  #        uses: docker/build-push-action@v5
  #        with:
  #          file: ./artifacts/backend/Dockerfile
  #          github-token: ${{ secrets.GHCR_PUBLISH_TOKEN }}
  #          push: true
  #          context: .
  #          tags: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}-post
  #          build-args: |
  #            "GH_BUILD_NUMBER=${{ github.run_number }}"
  notification:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: send message
#        run: echo HW!
        uses: ./.github/actions/loop-send-message
        with:
          build-number: ${{github.run_number}}
