name: build and deploy live translation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo stuff'
        run: echo 'build'
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy'
