name: 'Build and deploy app :)'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'build'
  deploy:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - run: echo 'deployy!'
