name: Deploy
on:
  workflow_call:
    inputs:
      image_number:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image_number:
        description: Image number
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: human-atalanta
          service-name: devschool-ci-test
          service-instance-type: free
          docker: ghcr.io/selfdeceited/devschool-ci-test:${{ inputs.image_number }}-postfix
          docker-private-registry-secret: ghrc_cred