name: Build and deploy
on:
  push:
jobs:
  build:
    permissions:
      packages: write
    name: Build artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.100
      - name: Build
        run: dotnet build --configuration Release DevschoolCiTest.sln
      # - name: Test
      #  run: dotnet test
      - name: Publish artifacts
        run: dotnet publish --no-restore --no-build --configuration Release --output artifacts/backend devschool-ci-test.csproj
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: selfdeceited
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./artifacts/backend/Dockerfile
          github-token: ${{ secrets.GHCR_PUBLISH_TOKEN }}
          push: true
          context: .
          tags: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: human-atalanta
          service-name: devschool-ci-test
          service-instance-type: free
          docker: ghcr.io/selfdeceited/devschool-ci-test:${{ github.run_number }}
          docker-private-registry-secret: ghrc_cred